#!/bin/bash

. $HOME/bin/scripts/jdk-switch.sh

# Main
JDK=$1

case $JDK in
  7) switch_jdk $JDK7;;
  8) switch_jdk $JDK8;;
  9) switch_jdk $JDK9;;
  10) switch_jdk $JDK10;;
  11) switch_jdk $JDK11;;
  13) switch_jdk $JDK13;;
  15) switch_jdk $JDK15;;
esac
